name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Build OpenCV
      run: |
        git clone https://github.com/opencv/opencv.git -b 3.4.16 --depth 1
        git clone https://github.com/opencv/opencv_contrib.git -b 3.4.16 --depth 1
        cmake -S opencv -B opencv/build -G "Visual Studio 17 2022" -D CMAKE_GENERATOR_PLATFORM=Win32 -D OPENCV_EXTRA_MODULES_PATH=./opencv_contrib/modules
        cmake --build opencv/build --config Release

    - name: Build MotionTracking_MKII_Plus
      run: |
        cmake -S src -B src/build -G "Visual Studio 17 2022" -D CMAKE_GENERATOR_PLATFORM=Win32
        cmake --build opencv/build --config Release