name: CI

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Build OpenCV
      run: |
        git clone https://github.com/opencv/opencv.git -b 3.4.16 --depth 1
        git clone https://github.com/opencv/opencv_contrib.git -b 3.4.16 --depth 1
        cmake -S opencv -B opencv/build -G "Visual Studio 17 2022" -D CMAKE_GENERATOR_PLATFORM=Win32 -D OPENCV_EXTRA_MODULES_PATH=./opencv_contrib/modules -D BUILD_SHARED_LIBS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D WITH_WEBP=OFF -D WITH_TIFF=OFF -D WITH_QUIRC=OFF -D WITH_PROTOBUF=OFF -D WITH_OPENEXR=OFF -D WITH_JPEG=OFF -D WITH_LAPACK=OFF -D WITH_JASPER=OFF -D WITH_PNG=OFF -D WITH_GSTREAMER=OFF -D WITH_FFMPEG=OFF -D WITH_EIGEN=OFF -D WITH_DSHOW=OFF -D WITH_DIRECTX=OFF -D WITH_ARITH_DEC=OFF -D WITH_ARITH_ENC=OFF -D WITH_1394=OFF -D WITH_IMGCODEC_HDR=OFF -D WITH_IMGCODEC_PXM=OFF -D WITH_IMGCODEC_SUNRASTER=OFF -D BUILD_JASPER=OFF -D BUILD_JAVA=OFF -D BUILD_JPEG=OFF -D BUILD_OPENEXR=OFF -D BUILD_PNG=OFF -D BUILD_PROTOBUF=OFF -D BUILD_TBB
        cmake --build opencv/build --config Release

    - name: Build MotionTracking_MKII_Plus
      run: |
        cmake -S src -B src/build -G "Visual Studio 17 2022" -D CMAKE_GENERATOR_PLATFORM=Win32 -D OPENCV_INCLUDE_DIR=opencv/build/install/include -D OPENCV_LIBRARY_DIR=opencv/build/install/x86/vc17/staticlib
        cmake --build opencv/build --config Release